c:\MyStuff\CodingProjects\enigmaCOA\trainModelLogisticRegression.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame
See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.y.loc[self.y.index[i]] = 0
epoch: 1, loss = 0.7204
epoch: 2, loss = 0.9805
epoch: 3, loss = 0.8131
epoch: 4, loss = 0.8977
epoch: 5, loss = 0.8146
epoch: 6, loss = 1.0851
epoch: 7, loss = 0.7210
epoch: 8, loss = 0.7729
epoch: 9, loss = 0.7920
epoch: 10, loss = 0.9545
epoch: 11, loss = 0.7255
epoch: 12, loss = 1.0649
epoch: 13, loss = 0.6760
epoch: 14, loss = 0.6898
epoch: 15, loss = 0.7430
epoch: 16, loss = 0.9864
epoch: 17, loss = 0.6946
epoch: 18, loss = 0.8050
epoch: 19, loss = 0.7155
epoch: 20, loss = 0.9106
epoch: 21, loss = 0.6556
epoch: 22, loss = 0.8887
epoch: 23, loss = 0.6435
epoch: 24, loss = 1.0409
epoch: 25, loss = 0.6495
epoch: 26, loss = 0.6069
epoch: 27, loss = 0.7114
epoch: 28, loss = 0.8940
epoch: 29, loss = 0.6390
epoch: 30, loss = 0.7419
epoch: 31, loss = 0.6582
epoch: 32, loss = 0.9399
epoch: 33, loss = 0.6065
epoch: 34, loss = 0.6428
epoch: 35, loss = 0.6897
epoch: 36, loss = 0.8284
epoch: 37, loss = 0.6099
epoch: 38, loss = 0.8378
epoch: 39, loss = 0.5931
epoch: 40, loss = 0.7228
epoch: 41, loss = 0.6246
epoch: 42, loss = 0.9155
epoch: 43, loss = 0.5618
epoch: 44, loss = 0.5857
epoch: 45, loss = 0.6426
epoch: 46, loss = 0.8492
epoch: 47, loss = 0.5824
epoch: 48, loss = 0.6613
epoch: 49, loss = 0.6182
epoch: 50, loss = 0.7614
epoch: 51, loss = 0.5679
epoch: 52, loss = 0.7827
epoch: 53, loss = 0.5478
epoch: 54, loss = 0.6280
epoch: 55, loss = 0.6081
epoch: 56, loss = 0.8687
epoch: 57, loss = 0.5500
epoch: 58, loss = 0.5713
epoch: 59, loss = 0.6144
epoch: 60, loss = 0.6990
epoch: 61, loss = 0.5701
epoch: 62, loss = 0.7323
epoch: 63, loss = 0.5351
epoch: 64, loss = 0.6325
epoch: 65, loss = 0.5663
epoch: 66, loss = 0.8058
epoch: 67, loss = 0.5179
epoch: 68, loss = 0.5592
epoch: 69, loss = 0.5891
epoch: 70, loss = 0.6988
epoch: 71, loss = 0.5315
epoch: 72, loss = 0.6474
epoch: 73, loss = 0.5385
epoch: 74, loss = 0.6951
epoch: 75, loss = 0.5147
epoch: 76, loss = 0.5828
epoch: 77, loss = 0.5528
epoch: 78, loss = 0.7657
epoch: 79, loss = 0.5024
epoch: 80, loss = 0.5461
epoch: 81, loss = 0.5622
epoch: 82, loss = 0.6513
epoch: 83, loss = 0.5183
epoch: 84, loss = 0.6283
epoch: 85, loss = 0.5137
epoch: 86, loss = 0.6222
epoch: 87, loss = 0.5114
epoch: 88, loss = 0.6179
epoch: 89, loss = 0.5089
epoch: 90, loss = 0.6115
epoch: 91, loss = 0.5066
epoch: 92, loss = 0.6087
epoch: 93, loss = 0.5035
epoch: 94, loss = 0.5940
epoch: 95, loss = 0.5040
epoch: 96, loss = 0.6080
epoch: 97, loss = 0.4963
epoch: 98, loss = 0.5670
epoch: 99, loss = 0.5044
epoch: 100, loss = 0.6181
accuracy = 0.8257
Traceback (most recent call last):
  File "c:\MyStuff\CodingProjects\enigmaCOA\trainModelLogisticRegression.py", line 126, in <module>
    wandb.log(f'accuracy{acc}')
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_run.py", line 394, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_run.py", line 345, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_run.py", line 335, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_run.py", line 1751, in log
    self._log(data=data, step=step, commit=commit)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_run.py", line 1527, in _log
    raise ValueError("wandb.log must be passed a dictionary")
ValueError: wandb.log must be passed a dictionary